server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    # Auth Service Route
    location /api/auth {
        include fastcgi_params;
        fastcgi_pass auth_service:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;

        fastcgi_connect_timeout 60s;
        fastcgi_read_timeout 60s;
        fastcgi_send_timeout 60s;
    }

    # Order Service Route
    location /api/orders {
        include fastcgi_params;
        fastcgi_pass order_service:9000;
        fastcgi_param SCRIPT_FILENAME /var/www/public/index.php;
        fastcgi_param REQUEST_URI $request_uri;

        fastcgi_connect_timeout 60s;
        fastcgi_read_timeout 60s;
        fastcgi_send_timeout 60s;
    }
}
